### ISSUE TITLE
Koodikatselmointi, viikko3

### ISSUE THREAD

**Issue by mikkolei** [hajame/warehouse#1]
Sovellus näyttää olevan hyvin aluillaan. Koodi on selkeää kaikin puolin ja viikon 3 (ja aiempien viikkojen) tavoitteet on saavutettu. HTML-sivut vaikuttavat olevan (ainakin tämän hetkisten vaatimuksien mukaan) hyvin selkeitä ja navigointi on helppoa. Sovelluksen ulkoasu luultavammin ottaa askeleen entistä parempaan suuntaan seuraavien viikkojen aikana. 

Numeroiden validointi toteutettu erityisesti hyvin, eivätkä ne hyväksyneet erikoisempia syötteitä. Muissa validoinneissa olisi hyvä ottaa huomioon ainakin muutama seikka: liian pitkien syötteiden rajaaminen pois, ja ettei inputiksi kelpaa pelkät välilyönnit. Liian pitkät syötteet aiheuttivat ainakin error sivun ja välilyönnit kelpaavat kaikkiin input-kenttiin, jotka hyväksyvät muuta kuin numeroita.

Uuden käyttäjän luomisessa voisi olla käytössä toinen input kenttä salasanalle, varmistuakseen, että salasana on oikein kirjoitettu. Salasanat myös talletetaan selkokielisesti, eli ne kannattaisi hashata. 

Tavaroita ei voi poistaa vielä kokonaan, vaikka saldot olisivat nollissa. Tavarat eivät myöskään ole liitettyinä vielä varastoihin. Tavaroita (ja myös muita talletettavia) voi myös olla useampi samalla nimellä (uniikkeja syötteitä voisi käyttää osaan toiminnallisuuksista). Luultavammin nämä kuitenkin tulevat muuttumaan myöhemmin, muiden puuttuvien toiminnallisuuksien täydentämisen yhteydessä. 

Sovelluksessa on myös kaikki toiminnallisuus rajattu kirjautumisen taakse. On luultavasti tarkoituksen mukaista kyseisen ohjelman kannalta, mutta harjoitustyön kannalta voisi harkita, jos osan toiminnallisuudesta näkisi ilman kirjautumista, esim. varastojen ja tavaroiden määrät, ilman muokkaus- ja poisto-oikeuksia. 

Pienempiä huomautuksia:
Itemien listauksessa, otsikkona näkyy Ontario, vaikka itemit eivät ole yhdistettynä kyseiseen varastoon.
Muutamat "__pycache__" kansiot päätynyt gittiin, joten ne kannattaisi sieltä poistaa.
Readme.md pieni kirjoitusvirhe, kohdassa "Ylläpitäjän **oikeiuksilla** käyttäjä..."

Kaiken kaikkiaan sovellus vaikuttaa olevan hyvällä mallilla!

Sovellusta tarkasteltu maanantaina 13.8.2018 alkaen klo 15.00

**Comment by hajame** [comment]
Kiitos rakentavasta palautteestasi! Tuli monta hyvää pointtia, joilla voin kehittää sovellusta.
